
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.4 EDK_O.87xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_DIP_SWITCHES_8BITS_DEVICE_ID,
		XPAR_DIP_SWITCHES_8BITS_BASEADDR,
		XPAR_DIP_SWITCHES_8BITS_INTERRUPT_PRESENT,
		XPAR_DIP_SWITCHES_8BITS_IS_DUAL
	},
	{
		XPAR_SEVSEG_DISP_12BITS_DEVICE_ID,
		XPAR_SEVSEG_DISP_12BITS_BASEADDR,
		XPAR_SEVSEG_DISP_12BITS_INTERRUPT_PRESENT,
		XPAR_SEVSEG_DISP_12BITS_IS_DUAL
	}
};


